---

roles:
  - src: https://github.com/companieshouse/ansible-role-aws-nvme-device-files
    name: aws-nvme-device-files
    version: 1.0.0
  - src: https://github.com/geerlingguy/ansible-role-repo-epel
    name: epel
    version: 3.0.0
  - src: https://github.com/geerlingguy/ansible-role-pip
    name: pip
    version: 2.0.0

collections:
  - name: community.general
